### ISSUE TITLE
Update Docs

### ISSUE THREAD

**Issue by darkshadow0666** [AkaruiDevelopment/aoi.db#5]
Can you update docs to support v2?
- WideColumnar is called WideColumn in examples
- KeyValue shows v1 examples.
- I also think WideColumnar should have more examples as it seems a bit confusing to understand

**Comment by darkshadow0666** [comment]
@USERSATOSHI

**Comment by USERSATOSHI** [comment]
> Can you update docs to support v2?
> - WideColumnar is called WideColumn in examples
> - KeyValue shows v1 examples.
> - I also think WideColumnar should have more examples as it seems a bit confusing to understand

I think u meant Readme

Cause docs are updated

**Comment by USERSATOSHI** [comment]
But yes I will update them

**Comment by darkshadow0666** [comment]
Thank you ❤️ can you also give an example on .set/.get for WideColumnar?

These are the 2 I'm struggling with

**Comment by USERSATOSHI** [comment]
@darkshadow0666 docs have been updated some time ago
https://akaruidevelopment.github.io/aoi.db/classes/WideColumnar.html#set

you can do
```js
  <WideColumnar>.set("tablename", { name : "columnname like xp", value: 10 } , { name: "primary column like id", value: "some id here" })
```
